sudo : required
services:
    - docker

before_install:
    - docker build -t danishsattar/react-app-gradeflow -f Dockerfile.dev .

script:
    - docker run danishsattar/react-app-gradeflow npm run test -- --coverage
 
deploy:
    provider: elasticbeanstalk
    region: "us-west-2"
    app: "docker"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-bucket from s3"
    bucket_path: "docker"
on:
    branch: master
